### ISSUE TITLE
Website updates

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-website-legacy#2]
Update the background image (purple gradient included below)
Update the logo (Png included below though Ronit you might need to resize)
Update the fonts (Png of the current fonts below- the header fonts should be ostrich Sans Medium, and the body font should be Now-Alt Regular.)
Update the accent color to the orange The Rules included in their deck:
#F15626

We will need to revisit the site in more detail but this small facelift will do wonders for continuity with the app, etc.
links to the fonts:
https://fontlibrary.org/en/font/now-alt
https://www.fontsquirrel.com/fonts/ostrich-sans

**Comment by saraswathi** [comment]
Thanks Ed!
![circles-presentation-2 105 -about-us](https://user-images.githubusercontent.com/1209203/46630442-0f782680-caf9-11e8-9541-e9fb5ba13654.png)
![circles-presentation-2 106 -concept](https://user-images.githubusercontent.com/1209203/46630443-0f782680-caf9-11e8-8dc0-f3f80e901bd3.png)
<img width="987" alt="screen shot 2018-10-05 at 2 51 16 pm" src="https://user-images.githubusercontent.com/1209203/46630452-12731700-caf9-11e8-94ee-9f30452b8c50.png">

**Comment by edzillion** [comment]
Ok these updates aren't trivial due to the following:
* The original header is a svg image which is referenced in a css background on the `header` div. This means we need either an `svg` version of the logo (zoomed appropriately?) or need to add another div that sits under/at the bottom of the `header` and w appropriate css layout
* The background image is a gradient, this would be better achieved in pure css, but some thought needs to be put into how it is used, as the current design has alternating sections of white / grey. We could pick a purple colour and alternate between solid colour and gradient, but we'd also need to think about how tall the gradients should be etc.
* Font folder seems to be missing but that AFAIK is an easy fix

What do you think @saraswathi ?

**Comment by edzillion** [comment]
Fixed by https://github.com/CirclesUBI/circles-website/pull/3
